Home/urls.py
from Home import views
from django.urls import path
app_name='Home'

urlpatterns = [
    path('', views.home, name=''),
    path('show/', views.show, name='show'),
    path('reg/', views.reg, name='reg'),
    path('delete/<int:fid>', views.delete, name='delete'),
    path('edit/<int:fid>', views.edit, name='edit'),
    path('login/', views.login, name='login'),
]

mainproject/urls.py
from django.contrib import admin
from django.urls import path,include
from Home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
]

Home/models.py
from django.db import models

# Create your models here.

class Faculty(models.Model):
    faculty_id = models.IntegerField()
    faculty_name = models.CharField(max_length=30)
    faculty_place = models.CharField(max_length=30)
    faculty_position = models.CharField(max_length=40)
    faculty_email = models.CharField(max_length=40)
    faculty_password = models.CharField(max_length=40)

Home/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.core.mail import send_mail
# from Home.models import Faculty
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from Home.models import Faculty
from mainproject.settings import EMAIL_HOST_USER

# Create your views here.

def home(request):
    return render(request, 'homepage.html')

def show(request):
    obj  = Faculty.objects.all()
    return render(request, 'show.html', {"obj":obj})

def reg(request):
    if request.method == "GET":
        return render(request, "reg_form.html")
    else:

        id = request.POST.get("id")
        name = request.POST.get("name")
        place = request.POST.get("place")
        position = request.POST.get("position")
        email = request.POST.get("email")
        password = request.POST.get("password")
        Faculty.objects.create(faculty_id=id,faculty_name=name,faculty_place=place,faculty_position=position,faculty_email=email,faculty_password=password)
        User.objects.create_user(id=id,username=name,password=password,email=email)

        send_mail(
            "FLIPKART",
            "Registered Successfully",
            EMAIL_HOST_USER,
            [email],
            fail_silently=False,
        )

        return redirect('Home:show')

def delete(request, fid):
    Faculty.objects.get(faculty_id=fid).delete()
    return redirect('Home:show')

def edit(request, fid):
    if request.method == "GET":
        obj = Faculty.objects.get(faculty_id=fid)
        return render(request, 'edit.html', {"obj":obj})
    else:
        uid = request.POST.get("id")
        name = request.POST.get("name")
        place = request.POST.get("place")
        email = request.POST.get("email")
        position = request.POST.get("position")
        password = request.POST.get("password")
        Faculty.objects.filter(faculty_id=fid).update(faculty_id=uid,faculty_name=name,faculty_place=place,faculty_position=position,faculty_email=email,faculty_password=password)
        User.objects.filter(id=fid).update(username=name,email=email,password=password)

        send_mail(
            "FLIPKART",
            "Details Updated",
            EMAIL_HOST_USER,
            [email],
            fail_silently=False,
        )

        return redirect('Home:show')

def login(request):
    if request.method == "GET":
        return render(request, 'login.html')
    else:
        uname = request.POST.get("uname")
        password = request.POST.get("password")
        user = authenticate(username=uname, password=password)
        if user is not None:
            return HttpResponse("success")
        else:
            return HttpResponse("fail")

templates/bootstrap.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=\, initial-scale=1.0">
    <title>Registration</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Latest compiled JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <style>
        body{
            display: flex;
            justify-content: center;
            align-items: center;
        }
    </style>
</head>
<body>
    <form action="{% url 'Home:edit' obj.faculty_id %}" method="POST">
        {% csrf_token %}
        <h3 class="h3 text-success">EDIT DETAILS</h3>
        <input type="number" placeholder="Enter Your ID" name="id" value="{{ obj.faculty_id }}"><br><br>
        <input type="text" placeholder="Enter Your Name" name="name" value="{{ obj.faculty_name }}"><br><br>
        <input type="text" placeholder="Enter Your Place" name="place" value="{{ obj.faculty_place }}"><br><br>
        <input type="email" placeholder="Enter Your Email" name="email" value="{{ obj.faculty_email }}"><br><br>
        <select name="position">
            <option value="Junior Developer">Junior Developer</option>
            <option value="Senior Developer">Senior Developer</option>
            <option value="Senior Trainer">Senior Trainer</option>
            <option value="Junior Trainer">Junior Trainer</option>
        </select><br><br>
        <input type="text" placeholder="Enter Your Password" name="password" value="{{ obj.faculty_password }}"><br><br>
        <input type="submit">
    </form>
</body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% include 'bootstrap.html' %}
</head>
<body>
    <a href="{% url 'Home:login' %}"><button class="btn btn-primary m-3">Log In</button></a>
    <a href="{% url 'Home:reg' %}"><button class="btn btn-primary m-3">Register</button></a>
    <a href="{% url 'Home:show' %}"><button class="btn btn-primary m-3">View Users</button></a>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LogIn</title>
    {% include 'bootstrap.html' %}
</head>
<body>
    <form action="" method="POST" class="m-5">
        {% csrf_token %}
        <input type="text" placeholder="Enter Your UserName" name="uname"><br><br>
        <input type="text" placeholder="Enter Your Password" name="password"><br><br>
        <button class="btn btn-success">Log In</button>
    </form>
</body>
</html>

templates/reg_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=\, initial-scale=1.0">
    <title>Registration</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Latest compiled JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <style>
        body{
            display: flex;
            justify-content: center;
            align-items: center;
        }
    </style>
</head>
<body>
    <form action="{% url 'Home:reg' %}" method="POST">
        {% csrf_token %}
        <h3 class="h3 text-success">REGISTRATION FORM</h3>
        <input type="number" placeholder="Enter Your ID" name="id" min="0"><br><br>
        <input type="text" placeholder="Enter Your Name" name="name"><br><br>
        <input type="text" placeholder="Enter Your Place" name="place"><br><br>
        <input type="email" placeholder="Enter Your Email" name="email"><br><br>
        <select name="position">
            <option value="Junior Developer">Junior Developer</option>
            <option value="Senior Developer">Senior Developer</option>
            <option value="Senior Trainer">Senior Trainer</option>
            <option value="Junior Trainer">Junior Trainer</option>
        </select><br><br>
        <input type="text" placeholder="Enter Your Password" name="password"><br><br>
        <input type="submit">
    </form>
</body>
</html>

templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Details</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Latest compiled JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <table class="table table-success table-bordered">
        <tr class="text-primary h5">
            <td>ID</td>
            <td>NAME</td>
            <td>PLACE</td>
            <td>POSITION</td>
            <td>EMAIL</td>
            <td>PASSWORD</td>
            <td></td>
            <td></td>
        </tr>
        {% for i in obj %}
            <tr class="h6">
                <td>{{ i.faculty_id }}</td>
                <td>{{ i.faculty_name }}</td>
                <td>{{ i.faculty_place }}</td>
                <td>{{ i.faculty_position }}</td>
                <td>{{ i.faculty_email }}</td>
                <td>{{ i.faculty_password }}</td>
                <td><a href="{% url 'Home:edit' i.faculty_id %}">Edit</a></td>
                <td><a href="{% url 'Home:delete' i.faculty_id %}">Delete</a></td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>